#!/bin/bash
set -e

DB_USER=${DB_USER:-user}
DB_USER_PASS=${DB_USER_PASS:-CHANGEME}

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $DB_USER WITH PASSWORD '$DB_USER_PASS';

    GRANT CONNECT ON DATABASE $POSTGRES_DB TO $DB_USER;
    GRANT USAGE ON SCHEMA public TO $DB_USER;

    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO $DB_USER;

    ALTER DEFAULT PRIVILEGES FOR ROLE $POSTGRES_USER IN SCHEMA public 
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO $DB_USER;
EOSQL
